function write_touchstone_nport(filePath, freq, S, z0)
%WRITE_TOUCHSTONE_NPORT Write N-port S-parameters in Touchstone v1 RI form.

if nargin < 4 || isempty(z0)
    z0 = 50;
end

[outDir, ~, ext] = fileparts(filePath);
if ~isempty(outDir) && ~exist(outDir, 'dir')
    mkdir(outDir);
end

tokens = regexp(lower(ext), '^\.s(\d+)p$', 'tokens', 'once');
if isempty(tokens)
    error('Output file must use a .sNp extension: %s', filePath);
end
nPorts = str2double(tokens{1});

if size(S, 1) ~= nPorts || size(S, 2) ~= nPorts
    error('S matrix size does not match extension for %s', filePath);
end

fid = fopen(filePath, 'w');
if fid < 0
    error('Unable to open Touchstone file for writing: %s', filePath);
end

cleanup = onCleanup(@() fclose(fid));

fprintf(fid, '! Generated by Phase II Calibration\n');
fprintf(fid, '# Hz S RI R %.12g\n', z0);

nFreq = numel(freq);
for idxFreq = 1:nFreq
    rowMajor = reshape(permute(S(:, :, idxFreq), [2, 1]), 1, []);
    fprintf(fid, '%.12g', freq(idxFreq));
    for idxVal = 1:numel(rowMajor)
        fprintf(fid, ' %.12g %.12g', real(rowMajor(idxVal)), imag(rowMajor(idxVal)));
        if mod(idxVal, nPorts) == 0 && idxVal < numel(rowMajor)
            fprintf(fid, '\n');
        end
    end
    fprintf(fid, '\n');
end
end
