function config = phase1_config(rawDataDir, touchstoneDir, matDir)
%PHASE1_CONFIG Shared configuration for Phase I extraction.

config = struct();
config.raw_data_dir = rawDataDir;
config.touchstone_output_dir = touchstoneDir;
config.mat_output_dir = matDir;

config.band_names = {'0-67', '67-115', '110-170'};
config.band_keys = {'BAND_0_67', 'BAND_67_115', 'BAND_110_170'};

config.line_length_m = 25.44e-6;
config.eps_eff = 3.7245;
config.z0 = 50;
config.zc = 50;
config.alpha_np_per_m = 0;
config.alpha_search_np_per_m = linspace(0, 1500, 11);
config.eps_eff_search = linspace(3.2, 4.2, 11);
config.zc_search = linspace(40, 65, 11);
config.alpha_refine_halfspan_np_per_m = 150;
config.eps_eff_refine_halfspan = 0.12;
config.zc_refine_halfspan = 3;
config.alpha_refine_points = 9;
config.eps_eff_refine_points = 9;
config.zc_refine_points = 9;
config.use_parallel = true;
config.alpha_fit_weights = struct( ...
    'open_short_passivity', 100, ...
    'open_short_target', 20, ...
    'load_magnitude', 2, ...
    'straight_line_match', 20, ...
    'straight_return_loss', 10, ...
    'embedding_passivity', 30, ...
    'alpha_regularization', 5, ...
    'eps_regularization', 2, ...
    'zc_regularization', 2);
config.alpha_regularization_center_np_per_m = 250;
config.alpha_regularization_scale_np_per_m = 250;
config.eps_eff_regularization_center = 3.7245;
config.eps_eff_regularization_scale = 0.2;
config.zc_regularization_center = 50;
config.zc_regularization_scale = 5;
config.embedding_refine_with_sol = true;
config.embedding_refine_weights = struct( ...
    'open_short_passivity_p1', 180, ...
    'open_short_target_p1', 45, ...
    'load_magnitude_p1', 30, ...
    'open_short_passivity_p2', 180, ...
    'open_short_target_p2', 45, ...
    'load_magnitude_p2', 30, ...
    'thru_reconstruct', 140, ...
    'p34_line_match', 50, ...
    'p34_return_loss', 25, ...
    'baseline_s11', 90, ...
    'baseline_s22', 120, ...
    'smoothness_s11', 35, ...
    'smoothness_s22', 45, ...
    'embedding_passivity_mean', 90, ...
    'embedding_passivity_local', 180);
config.embedding_refine_max_iter = 80;
config.embedding_refine_max_fun_evals = 250;
config.embedding_refine_edge_span_hz = 5e9;
config.embedding_refine_edge_boost = 0.9;
config.embedding_refine_overlap_windows_hz = [63e9, 70e9; 112e9, 118e9];
config.embedding_refine_overlap_boost = 0.8;
config.sol_passivity_enforcement = false;
config.sol_passivity_target = 0.999;
config.sol_passivity_smoothing_window = 7;

config.supported_standard_types = {'short', 'open', 'load'};
config.supported_geometries = {'straight', 'arc', 'diagonal', 'diag'};
end
