function write_touchstone_2port(filename, freq, sParams, z0)
%WRITE_TOUCHSTONE_2PORT Write a .s2p file in RI format.

fid = fopen(filename, 'w');
if fid == -1
    error('Unable to create Touchstone file: %s', filename);
end

cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '! Generated by Phase I extraction\n');
fprintf(fid, '# Hz S RI R %.15g\n', z0);
for idx = 1:numel(freq)
    s11 = sParams(1, 1, idx);
    s21 = sParams(2, 1, idx);
    s12 = sParams(1, 2, idx);
    s22 = sParams(2, 2, idx);
    fprintf(fid, ...
        '%.15e %.15e %.15e %.15e %.15e %.15e %.15e %.15e %.15e\n', ...
        freq(idx), ...
        real(s11), imag(s11), ...
        real(s21), imag(s21), ...
        real(s12), imag(s12), ...
        real(s22), imag(s22));
end
end
