function write_touchstone_1port(filename, freq, gamma, z0)
%WRITE_TOUCHSTONE_1PORT Write a .s1p file in RI format.

fid = fopen(filename, 'w');
if fid == -1
    error('Unable to create Touchstone file: %s', filename);
end

cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '! Generated by Phase I extraction\n');
fprintf(fid, '# Hz S RI R %.15g\n', z0);
for idx = 1:numel(freq)
    fprintf(fid, '%.15e %.15e %.15e\n', freq(idx), real(gamma(idx)), imag(gamma(idx)));
end
end
